version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - nodebackend
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - web-app

  nodebackend:
    build:
      context: ./app
      dockerfile: dockerfile.back
    ports:
      - "5500:5500"
    container_name: nodebackend
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - web-app
    stdin_open: true
    tty: true
networks:
  web-app:
    driver: bridge
